version: '3'
services:
  backend:
    container_name: VoQuiz-GPT
    build:
      dockerfile: docker/Dockerfile
      context: .
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./
        target: /app
    command: python ./src/main.py
    tty: true
    restart: always
